# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'SQL CRUD App Demo',  url: 'SQL-App-by-Aashay'}
- {name: 'Integrating AI - Chatbot Assistants and AshGPT', url: 'ai'}
- {name: 'Understanding the History of Databases',       url: 'History-of-Databases'}
- {name: 'Data Engineering Project: Importing and Processing Data with AWS',      url: 'Data-Engineering-Project'}
- {name: 'About',              url: 'about'}
- {name: 'Boston Neighborhood Analysis',            url: 'Project-Boston'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com'}
- {icon: 'facebook', link:   'https://www.facebook.com'}
- {icon: 'instagram', link:  'https://instagram.com'}
- {icon: 'envelope', link:   'zende.a@northeastern.edu'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
